LeanCloudTests/ObjectTestCase.swift
LeanCloudTests/TypeTestCase.swift
Sources/Storage/DataType/ACL.swift
Sources/Storage/DataType/Array.swift
Sources/Storage/DataType/Bool.swift
Sources/Storage/DataType/Data.swift
Sources/Storage/DataType/Date.swift
Sources/Storage/DataType/Dictionary.swift
Sources/Storage/DataType/GeoPoint.swift
Sources/Storage/DataType/Null.swift
Sources/Storage/DataType/Number.swift
Sources/Storage/DataType/Object.swift
Sources/Storage/DataType/Relation.swift
Sources/Storage/DataType/String.swift
Sources/Storage/ObjectProfiler.swift
Sources/Storage/Value.swift

Now, LCType has some handy methods to directly get value of Swift-builtin type.

Make type conversion easier

---

LeanCloud.xcodeproj/project.pbxproj
Sources/Storage/Logger.swift

Add logger to print debug information.

Add logger

---

LeanCloud.podspec
Sources/Storage/LeanCloud.swift

Bump version to 10.0.1

---

Sources/Storage/CQLClient.swift
Sources/Storage/DataType/Object.swift
Sources/Storage/Query.swift

改进了 Query 和 CQL client 中与网络相关的方法，这是对 PR #69 的补充。
@zapcannon87 @leancloud/sdk-only

Improve network related apis for query and CQL client

---

LeanCloud.xcodeproj/project.pbxproj
LeanCloudTests/APITestCase.swift
Sources/Storage/Engine.swift
Sources/Storage/Extension.swift
Sources/Storage/SMSClient.swift

改进了云引擎和短信中与网络相关的方法，这是对 PR #69 的补充。
@zapcannon87 @leancloud/sdk-only

Improve network related apis for engine and short message

---

LeanCloud.xcodeproj/project.pbxproj
LeanCloudTests/APITestCase.swift
LeanCloudTests/RouterTestCase.swift
Sources/Storage/Application.swift
Sources/Storage/BatchRequest.swift
Sources/Storage/CQLClient.swift
Sources/Storage/DataType/Data.swift
Sources/Storage/DataType/Date.swift
Sources/Storage/DataType/Dictionary.swift
Sources/Storage/DataType/GeoPoint.swift
Sources/Storage/DataType/Relation.swift
Sources/Storage/DataType/User.swift
Sources/Storage/Engine.swift
Sources/Storage/Error.swift
Sources/Storage/Extension.swift
Sources/Storage/HTTPClient.swift
Sources/Storage/HTTPRouter.swift
Sources/Storage/Logger.swift
Sources/Storage/ObjectProfiler.swift
Sources/Storage/ObjectUpdater.swift
Sources/Storage/Query.swift
Sources/Storage/RESTClient.swift
Sources/Storage/Request.swift
Sources/Storage/Result.swift
Sources/Storage/SMSClient.swift

为数据存储增加了 app router。
@zapcannon87 @leancloud/sdk-only

Add HTTP router to route request to API module.

---

Sources/Storage/DataType/File.swift

Make LCFile public

---

Sources/Storage/HTTPClient.swift
Sources/Storage/ObjectProfiler.swift

在 HTTP 响应日志中增加了状态码和错误描述。 @zapcannon87

Make HTTP response log verbose.

---

Sources/Foundation/Error.swift
Sources/Storage/BatchRequest.swift
Sources/Storage/CQLClient.swift
Sources/Storage/DataType/ACL.swift
Sources/Storage/DataType/Array.swift
Sources/Storage/DataType/Bool.swift
Sources/Storage/DataType/Data.swift
Sources/Storage/DataType/Date.swift
Sources/Storage/DataType/Dictionary.swift
Sources/Storage/DataType/GeoPoint.swift
Sources/Storage/DataType/Null.swift
Sources/Storage/DataType/Number.swift
Sources/Storage/DataType/Object.swift
Sources/Storage/DataType/Relation.swift
Sources/Storage/DataType/String.swift
Sources/Storage/DataType/User.swift
Sources/Storage/Engine.swift
Sources/Storage/Extension.swift
Sources/Storage/FileUploader.swift
Sources/Storage/ObjectProfiler.swift
Sources/Storage/ObjectUpdater.swift
Sources/Storage/Operation.swift
Sources/Storage/Query.swift
Sources/Storage/Response.swift
Sources/Storage/Result.swift
Sources/Storage/Runtime.swift
Sources/Storage/SMSClient.swift
Sources/Storage/Utility.swift
Sources/Storage/Value.swift

消除了所有可以消除的 AnyObject 类型。 @zapcannon87 
https://github.com/apple/swift-evolution/blob/master/proposals/0116-id-as-any.md

Remove AnyObject type.

---

LeanCloudTests/ObjectTestCase.swift
Sources/Storage/DataType/Dictionary.swift
Sources/Storage/DataType/Object.swift
Sources/Storage/Value.swift

支持动态成员查询。 @zapcannon87 
https://github.com/apple/swift-evolution/blob/master/proposals/0195-dynamic-member-lookup.md

Support dynamic member lookup.

---

Sources/Foundation/Error.swift

支持让 LCError 表示底层错误。 @zapcannon87

Support underlying error.

---

LeanCloud.xcodeproj/project.pbxproj
LeanCloudTests/RTMTestCase.swift
Sources/IM/RTMRouter.swift
Sources/IM/RTMRouterCache.swift
Sources/IM/RTMRouterCache.xcdatamodeld/RTMRouterCache.xcdatamodel/contents
Sources/Storage/HTTPClient.swift
Sources/Storage/HTTPRouter.swift
Sources/Storage/Result.swift

支持了 RTM router 及其缓存。 @zapcannon87

Implement RTM router.

---

LeanCloud.xcodeproj/project.pbxproj
LeanCloudTests/ConnectionTestCase.swift
RuntimeTests-iOS/AppDelegate.swift
RuntimeTests-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
RuntimeTests-iOS/Assets.xcassets/Contents.json
RuntimeTests-iOS/Base.lproj/LaunchScreen.storyboard
RuntimeTests-iOS/Base.lproj/Main.storyboard
RuntimeTests-iOS/ConnectionTestViewController.swift
RuntimeTests-iOS/Info.plist
RuntimeTests-iOS/ViewController.swift
Sources/Foundation/Application.swift
Sources/Foundation/Error.swift
Sources/Foundation/Logger.swift
Sources/IM/Connection.swift
Sources/Storage/HTTPClient.swift
Sources/Storage/LeanCloud.swift

* Connection 接入了 RTM Router，Logger
* Connection 明确了回调的 Error
* Connection 完善了重连的处理逻辑
* LCError 补充了一些内部错误码
* Logger 增加了 verbose 级别
* 增加了一个 App Target 用来测试 Runtime 环境
* 为了 App Target 能编译通过，用 `struct LeanCloudConstant` 包裹了 `LeanCloud.swift` 中的 `version` （我拍脑袋决定的，应该没什么大问题吧）
* 接口有个小变动，`CommandCallback.Result.error` 的 value 由 `Error` 变为 `LCError` 了
@tang3w

Connection.swift is complete

---

Sources/IM/Connection.swift

重连机制小改动
* **Previous**：除了 WebSocket 的 `close op` 和协议错误以及 Socket 的 `closed by remote peer`，其它任何引起 socket 关闭的错误都应该触发**尝试重连机制**
* **Now**： 除了 WebSocket 的 `close op` 和协议错误，其它任何引起 socket 关闭的错误都应该触发**尝试重连机制**
主要是因为判断不了 Socket 的 closing 是不是由服务器发起的，某些网络原因也可能导致 `closed by remote peer`。

Tweak for auto reconnection

---

Sources/Storage/DataType/Installation.swift

增加了显式设置 installation 属性的方法。 @zapcannon87

Add a method for setting required installation properties.

---

LeanCloudTests/InstallationTestCase.swift

更新了一个 Installation 的测试用例。 @zapcannon87

Update a test case for Installation.

---

LeanCloud.podspec
Sources/Storage/LeanCloud.swift

Bump version to 15.0.0

---

LeanCloud.xcodeproj/project.pbxproj
Sources/IM/Client.swift
Sources/IM/Conversation.swift
Sources/Storage/ObjectProfiler.swift
Sources/Storage/Result.swift

支持创建普通对话、聊天室和临时对话。 @zapcannon87

Support to create conversation.

---

LeanCloud.podspec
LeanCloudTests/BaseTestCase.swift
LeanCloudTests/IMClientTestCase.swift
LeanCloudTests/IMConversationTestCase.swift
LeanCloudTests/IMMessageTestCase.swift
LeanCloudTests/RTMConnectionTestCase.swift
Sources/Foundation/LeanCloud.swift
Sources/IM/IMClient.swift
Sources/IM/IMConversation.swift
Sources/IM/RTMConnection.swift
Sources/Storage/Extension.swift

https://github.com/leancloud/swift-sdk/issues/180
https://github.com/leancloud/swift-sdk/issues/169

release: 16.0.0-beta.5

---

.gitmodules
LeanCloud.xcodeproj/project.pbxproj
LeanCloudTests/IMConversationTestCase.swift
LeanCloudTests/IMLocalStorageTestCase.swift
LeanCloudTests/IMMessageTestCase.swift
LeanCloudTests/LCUserTestCase.swift
LeanCloudTests/RTMBaseTestCase.swift
Sources/IM/IMClient.swift
Sources/IM/IMConversation.swift
Sources/IM/IMConversationQuery.swift
Sources/IM/IMLocalStorage.swift
Sources/IM/IMMessage.swift
Sources/Storage/Foundation/Logger.swift
Sources/Storage/LocalStorage/LocalStorage.swift

https://github.com/leancloud/swift-sdk/issues/177

IM support local storage

---

Sources/IM/RTMRouter.swift
Sources/Storage/DataType/Installation.swift
Sources/Storage/Foundation/Application.swift
Sources/Storage/HTTPClient.swift
Sources/Storage/HTTPRouter.swift
Sources/Storage/LocalStorage/LocalStorage.swift

https://github.com/leancloud/swift-sdk/issues/190

refactor: App Router cache

---

LeanCloud.xcodeproj/project.pbxproj
Sources/Storage/CaptchaClient.swift
Sources/Storage/SMSClient.swift

https://github.com/leancloud/swift-sdk/issues/187
https://github.com/leancloud/swift-sdk/issues/186
https://github.com/leancloud/swift-sdk/issues/184

feat: Support Captcha

---

LeanCloud.podspec
LeanCloudTests/IMConversationTestCase.swift
LeanCloudTests/IMMessageTestCase.swift
LeanCloudTests/LCInstallationTestCase.swift
LeanCloudTests/RTMConnectionTestCase.swift
Sources/IM/IMClient.swift
Sources/IM/IMConversation.swift
Sources/IM/RTMConnection.swift
Sources/Storage/CaptchaClient.swift
Sources/Storage/Foundation/Application.swift
Sources/Storage/Foundation/LeanCloud.swift
Sources/Storage/HTTPClient.swift

https://github.com/leancloud/swift-sdk/issues/171

release: 16.0.0-beta.6

---

LeanCloud.podspec
LeanCloudTests/IMClientTestCase.swift
LeanCloudTests/IMLocalStorageTestCase.swift
LeanCloudTests/IMMessageTestCase.swift
LeanCloudTests/LCUserTestCase.swift
Sources/IM/IMClient.swift
Sources/IM/IMConversation.swift
Sources/IM/IMLocalStorage.swift
Sources/IM/IMMessage.swift
Sources/Storage/DataType/File.swift
Sources/Storage/FileUploader.swift
Sources/Storage/Foundation/LeanCloud.swift

https://github.com/leancloud/swift-sdk/issues/198

release: 16.0.0

---

LeanCloud.podspec
README.md
Sources/Storage/Foundation/Application.swift
Sources/Storage/Foundation/LeanCloud.swift
Sources/Storage/HTTPRouter.swift

https://github.com/leancloud/swift-sdk/issues/195

feat: support custom server

---

LeanCloud.podspec
LeanCloudTests/LCUserTestCase.swift
Sources/IM/IMConversation.swift
Sources/IM/IMConversationQuery.swift
Sources/Storage/DataType/User.swift
Sources/Storage/Extension.swift
Sources/Storage/Foundation/LeanCloud.swift

https://github.com/leancloud/swift-sdk/issues/163

release: 16.2.0

---

LeanCloudTests/LCObjectTestCase.swift
LeanCloudTests/LCQueryTestCase.swift
Sources/Storage/BatchRequest.swift
Sources/Storage/DataType/File.swift
Sources/Storage/DataType/Object.swift
Sources/Storage/DataType/User.swift
Sources/Storage/ObjectUpdater.swift
Sources/Storage/Query.swift

https://github.com/leancloud/swift-sdk/issues/118
https://github.com/leancloud/swift-sdk/issues/119
https://github.com/leancloud/swift-sdk/issues/201

add some feats for storage

---

LeanCloud.podspec
LeanCloudTests/IMClientTestCase.swift
LeanCloudTests/IMConversationTestCase.swift
LeanCloudTests/LCQueryTestCase.swift
Sources/IM/IMClient.swift
Sources/IM/IMConversation.swift
Sources/IM/IMConversationQuery.swift
Sources/IM/IMMessage.swift
Sources/Storage/CaptchaClient.swift
Sources/Storage/DataType/User.swift
Sources/Storage/Engine.swift
Sources/Storage/Foundation/LeanCloud.swift
Sources/Storage/Push.swift
Sources/Storage/Query.swift

https://github.com/leancloud/swift-sdk/issues/214

release: 16.4.0

---

LeanCloud.podspec
LeanCloud.xcodeproj/project.pbxproj
LeanCloud.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
LeanCloudTests/BaseTestCase.swift
LeanCloudTests/IMClientTestCase.swift
LeanCloudTests/IMConversationTestCase.swift
LeanCloudTests/IMMessageTestCase.swift
LeanCloudTests/LCLocalStorageContextTestCase.swift
LeanCloudTests/LCQueryTestCase.swift
LeanCloudTests/LCUserTestCase.swift
Package.swift
RuntimeTests-iOS/AppDelegate.swift
Sources/Foundation/Application.swift
Sources/Foundation/Extension.swift
Sources/Foundation/FileUploader.swift
Sources/Foundation/HTTPClient.swift
Sources/Foundation/LocalStorage.swift
Sources/Foundation/Query.swift
Sources/Foundation/User.swift
Sources/Foundation/Version.swift
Sources/RTM/IMConversation.swift
Sources/RTM/IMConversationQuery.swift
Sources/RTM/LiveQuery.swift

close https://github.com/leancloud/swift-sdk/issues/221
close https://github.com/leancloud/swift-sdk/issues/216

release: 17.1.0

---

README.md

Thank command.Zi for bringing this matter to our attention.

docs: update doc links in README

---

LeanCloudTests/IMConversationTestCase.swift
Sources/RTM/IMClient.swift
Sources/RTM/IMConversation.swift

feat(IM): padding raw data of conversation after creation

---

Sources/Foundation/Date.swift

feat(date): public iso string

---

Sources/Foundation/Query.swift
Sources/RTM/IMConversationQuery.swift

close https://github.com/leancloud/swift-sdk/issues/353

feat(query): make some properties public
