- Sources/Storage/DataType/Object.swift
There's no need to prefix `self` for accessing own property and method.
> Refine syntax for accessing property and method

- LeanCloudTests/ObjectTestCase.swift
- Sources/Storage/DataType/Dictionary.swift
- Sources/Storage/DataType/Object.swift
- Sources/Storage/Engine.swift
- Sources/Storage/ObjectProfiler.swift
- Sources/Storage/Operation.swift
改进对象的属性访问，确保在保存对象时，在构造方法中设置的属性不会漏掉。
> Refine object property access

- Sources/Storage/Runtime.swift
修复对类型进行相等性比较时 crash 的问题。导致问题的原因是应用引入了不可比较类型。例如 WebKit.framework 中的 WKObject 类型无法响应 `===` 运算符。修复方案是利用 ObjectIdentifier 进行比较。
@leancloud/ios-group @aisk
> Fix crash for identity test between non-equatable types

- LeanCloudTests/TypeTestCase.swift
- Sources/Storage/DataType/Object.swift
Make decoding initializer to call designated initializer to ensure complete initialization.
Refer to https://forum.leancloud.cn/t/swift-currentuser/14895
@leancloud/ios-group @BinaryHB
> Make object mutable after unarchiving

- Sources/Storage/Engine.swift
Reverts leancloud/swift-sdk#53
The REST API "call" is a RPC, unlike Objective-C SDK's `+[AVCloud call]`, which is not a RPC.
> Revert "Support LeanEngine RPC"

- LeanCloudTests/BaseTestCase.swift
- Sources/Storage/ObjectProfiler.swift
只注册内置的对象类型。这个改动要求开发者手动注册 object 类型，而不是 SDK 扫描应用中所有的类型来自动注册。做这个改动的原因是在模拟器中偶尔会崩溃，崩溃是因为 inspect 某个类时出现了 bad access，但不清楚造成 bad access 的具体原因。 @zapcannon87
> Only register built-in object classes.

- LeanCloudTests/APITestCase.swift
- LeanCloudTests/BaseTestCase.swift
添加了取消网络请求的测试用例。
@zapcannon87 @leancloud/sdk-only
> Add test cases for request cancellation.

- LeanCloud.xcodeproj/project.pbxproj
- LeanCloudTests/RouterTestCase.swift
- Sources/LocalStorage/LocalStorage.swift
- Sources/LocalStorage/PersistentController.swift
- Sources/Storage/AppRouterCache.swift
- Sources/Storage/AppRouterCache.xcdatamodeld/AppRouterCache.xcdatamodel/contents
- Sources/Storage/HTTPRouter.swift
为 App Router 增加了本地缓存。
以外，还实现了一个基于 Core Data 的持久层。选择 Core Data 的原因主要有：
1. Core Data 是 Apple 官方提供的存储方案；
2. Core Data 可以更轻松地管理对象图；
3. Core Data 提供了自动的轻量迁移。
存储性能还没有具体测试，不过从 Ray 的实际表现来看，还没有出现明显的性能瓶颈。
@zapcannon87
> Cache app router to file system.

- LeanCloud.podspec
- LeanCloud.xcodeproj/project.pbxproj
- LeanCloudTests/InstallationTestCase.swift
- Sources/Foundation/Application.swift
- Sources/Foundation/Lazyload.swift
- Sources/Foundation/Polyfill/Polyfill.h
- Sources/Foundation/Polyfill/Polyfill.m
- Sources/Foundation/Polyfill/module.modulemap
- Sources/Foundation/Polyfill/module.private.modulemap
- Sources/LocalStorage/LocalStorage.swift
- Sources/Storage/BatchRequest.swift
- Sources/Storage/DataType/Installation.swift
- Sources/Storage/DataType/Object.swift
- Sources/Storage/Extension.swift
- Sources/Storage/HTTPClient.swift
- Sources/Storage/ObjectProfiler.swift
- Sources/Storage/ObjectUpdater.swift
- Sources/Storage/StorageContext.xcdatamodeld/StorageContext.xcdatamodel/contents
- Sources/Storage/StorageContextCache.swift
支持了 Installation 及其缓存。目前 currentInstallation 是 Application 的一个属性。
@zapcannon87
> Support installation

- Sources/Storage/HTTPClient.swift
- Sources/Storage/HTTPRouter.swift
HTTPClient 和 HTTPRouter 并不是真的循环引用，我更新了注释。 @cavanlee
> Update comment for HTTP client and router.

- LeanCloud.podspec
- Sources/Storage/DataType/Object.swift
当使用 dot 语法访问成员时，Swift 会优先访问内置属性。
在 macOS 中，NSObject 刚好有一个名为 className 的内置属性，所以改用 subscript 来访问。
https://developer.apple.com/documentation/objectivec/nsobject/1411337-classname
> Fix confliction between dynamic lookup and built in property.

- Sources/IM/Connection.swift
- Sources/IM/RTMRouter.swift
- Sources/IM/RTMRouterCache.swift
- Sources/IM/RTMRouterCache.xcdatamodeld/RTMRouterCache.xcdatamodel/contents
* RTM Router 缓存增加了「创建时间」属性
* Connection 针对服务器错误做了以下更改
* 无论自动重连打开与否，由于服务器错误导致的 Primary Server 连接失败或断开，立即尝试连接 Secondary Server
* 由于服务器错误导致的 Secondary Server 连接失败或断开，如果当前时间已超过 RTM Router 缓存的创建时间 60 秒，清理 RTM Router 缓存。如果自动重连处于开启状态，在 10 秒后尝试重连。
* TCP reset 导致的断开视作服务器错误。
这个改动主要是为了解决「在 RTM Router 缓存没有过期，RTM Router 缓存的 Server 都因为服务器错误连接不上，而 RTM Router 已经切换到可用的 Server 时」，SDK 能够在较短的时间内自动清理无效缓存并能够不间断的尝试重连服务器。
上述的「60 秒」和「10 秒」是在和后端讨论后决定的。在 Runtime 环境测试过了，应该没问题。
@tang3w
>  Update Reconnection Strategy for Server Error

- LeanCloud.xcodeproj/project.pbxproj
- LeanCloud.xcodeproj/xcshareddata/xcschemes/LeanCloudTests.xcscheme
- LeanCloudTests/ClientTestCase.swift
- LeanCloudTests/ConnectionTestCase.swift
- RuntimeTests-iOS/Base.lproj/Main.storyboard
- RuntimeTests-iOS/ConnectionTestViewController.swift
- Sources/IM/Client.swift
- Sources/IM/Connection.swift
* LCClient 相关
* 重构了和 Session open & close 相关的部分
* 移除 SessionError，用 LCError 替代
* 支持了「单设备登录」
* 对应的单元测试
* Connection 移除 Error，用 LCError 替代
@tang3w
> Update LCClient & Connection

- Sources/Storage/DataType/Object.swift
If no amount is specified, increase by 1 by default.
This is consistent with other SDKs.
> Object.increase: by defaults to 1.

- LeanCloudTests/IMConversationTestCase.swift
- Sources/RTM/IMClient.swift
- Sources/RTM/IMConversation.swift
- Sources/RTM/IMConversationQuery.swift
> feat(IM): function for getting temporary conversation by id

- LeanCloudTests/IMMessageTestCase.swift
- Sources/Foundation/File.swift
- Sources/Foundation/FileUploader.swift
> feat(file): property option for keep file name

- LeanCloudTests/IMMessageTestCase.swift
- Sources/RTM/IMClient.swift
- Sources/RTM/IMConversation.swift
> feat(IM): last delivered & read date property, fetch receipt timestamp function for conversation

- LeanCloudTests/BaseTestCase.swift
- LeanCloudTests/IMConversationTestCase.swift
- LeanCloudTests/RTMConnectionTestCase.swift
- Sources/Foundation/Runtime.swift
- Sources/RTM/IMClient.swift
- Sources/RTM/LiveQueryClient.swift
- Sources/RTM/RTMConnection.swift
> feat(rtm): throttling command and omit peer-id

- Sources/Foundation/FileUploader.swift
ref: https://github.com/leancloud/rfcs/issues/1085
> chore: use file key generated by server

- Sources/RTM/IMConversation.swift
https://github.com/leancloud/rfcs/issues/1100
> feat: fetching member info support limit and offset
